# fly.toml app configuration file generated for detailing-shop on 2023-08-07T21:13:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "detailing-shop"
primary_region = "bos"

[build]
  image = "victordev12/detailing-shop:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloundName="de04qqilt"
  Cloudinary__ApiKey="466595765355674"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
